language: cpp
compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls

install:
  - make madx-linux64-gnu COVERAGE=yes
  - make numdiff-linux64-gnu

script:
  # Temporarily exclude test-plot until we can install gnuplot on the travis
  # docker container, see:
  # https://github.com/travis-ci/apt-package-whitelist/issues/3866
  - >-
    make tests tests-to-rm=test-plot &&
    NUM_FAILED=$(<tests/tests-summary.txt grep -o 'FAILED.*' | awk '{print $2}') &&
    [[ $NUM_FAILED = 0 ]]

after_success:
  - coveralls --include src -x .c -x .cpp


addons:
  apt:
    packages:
    - gfortran

git:
  # Limit cloning depth to reduce download bandwidth:
  # Please note that if you use a depth of 1 and have a queue of jobs, Travis
  # CI won’t build commits that are in the queue when you push a new commit.
  depth: 1

  # Don't clone the `examples/` submodule:
  submodules: false
